const PlacesList = {
    "places": [
        {
            "id": 94,
            "name": "Wonderla",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/pASuv3k4DM7dna6.jpeg",
            "official_description": "Wonderla Holidays Limited is a leading amusement park designing and operating company in India headquartered near Bidadi, 28 kilometres from Bangalore. It is promoted by Kochouseph Chittilappilly and his son Arun Chittilappilly. Wonderla's flagship amusement park located at the same address is the second theme park project from the company and has been operational since October 2005. It is spread over an area of 82 acres. The first amusement park, Wonderla Kochi, was set up in 2000. In 2016, the third project Wonderla Hyderabad is set up. The parks have been set up with a total investment of over ₹2.5 billion.",
            "location": "bengaluru",
            "latitude": 0,
            "longitude": 0,
            "pincode": "562109"
        },
        {
            "id": 17,
            "name": "Vuda Park",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "It is developed on the beachfront in an area of 55 acres. Out of which 37 acres covered with lawns, various species of flower plants, hedge plants and others. This park consists of around 2,500 shade-giving trees. It is the prominent recreation center for Vizagites and the visitors of Visakhapatnam. \r\n",
            "location": "Visakapatanam",
            "latitude": 17.724088,
            "longitude": 83.339529,
            "pincode": "530017"
        },
        {
            "id": 91,
            "name": "Vidhana Soudha",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/4611469-Vidhana_Soudha_Bangalore.jpg",
            "official_description": "The Vidhana Soudha located in Bengaluru  is the seat of the state legislature of Karnataka. It is an imposing building, constructed in a style sometimes described as Mysore Neo-Dravidian, and incorporates elements of Indo-Saracenic and Dravidian styles. The construction was completed in 1956.",
            "location": "bengaluru",
            "latitude": 125846.9,
            "longitude": 773526.37,
            "pincode": "560001"
        },
        {
            "id": 35,
            "name": "Vastrapur Lake",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Vastrapur Lake is situated in western part of Ahmedabad. It is officially named after Narsinh Mehta. The lake was beautified by the AMC after 2002 and has since become a popular spot in the city.Every weekend, a large number of people visit this lake. It currently boasts an open-air theater and children's park. There is a pathway all around the lake which serves many walkers and joggers in the early mornings and in the evenings.",
            "location": "Ahmedabad",
            "latitude": 23.038417,
            "longitude": 72.528802,
            "pincode": "380015"
        },
        {
            "id": 82,
            "name": "Vasant Vihar",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/250px-Front-facade_1.jpg",
            "official_description": "Vasant Vihar is a neighbourhood located in the South West Delhi district of National Capital Territory of Delhi. It is located near the diplomatic area of Chanakyapuri, and houses over 50 diplomatic missions of foreign countries.\r\n",
            "location": "Delhi",
            "latitude": 283326.64,
            "longitude": 77932.4,
            "pincode": "110070"
        },
        {
            "id": 39,
            "name": "Triund Hill",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Triund is the crown jewel of dharamshala , situated in the laps of dhauladhar mountains, it has the perfect view of the dhauladhar mountains on one side and kangra valley on the other. Triund is a very popular trekking spot . Triund attracts a lot of tourist every year from India and all over the world .   ",
            "location": "Dharamsala ",
            "latitude": 32.259582,
            "longitude": 76.356493,
            "pincode": " 17621"
        },
        {
            "id": 31,
            "name": "Tirumala Temple",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Sri Venkateswara Swamy Temple is a landmark vaishnavite temple situated in the hill town of Tirumala at Tirupati in Chittoor district of Andhra Pradesh, India. The Temple is dedicated to Lord Venkateswara, an incarnation of Vishnu, who is believed to have appeared here to save mankind from trials and troubles of Kali Yuga. Hence the place has also got the name Kaliyuga Vaikuntham and Lord here is referred to as Kaliyuga Prathyaksha Daivam.",
            "location": "Tirupathi",
            "latitude": 8.285829,
            "longitude": 77.175342,
            "pincode": "517504"
        },
        {
            "id": 52,
            "name": "Thikse Monastery",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "Thiksay Gompa or Thiksay Monastery is a gompa affiliated with the Gelug sect of Tibetan Buddhism. It is located on top of a hill in Thiksey village, approximately 19 kilometres east of Leh in Ladakh, India.",
            "location": "Leh",
            "latitude": 33.595849,
            "longitude": 78.293171,
            "pincode": "194101"
        },
        {
            "id": 47,
            "name": "The Ridge",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "The Ridge road is a large open space, located in the heart of Shimla, the capital city of Himachal Pradesh, India. The Ridge is the hub of all cultural activities of Shimla.",
            "location": "Shimla",
            "latitude": 31.104702,
            "longitude": 77.17396,
            "pincode": "171001"
        },
        {
            "id": 78,
            "name": "Teen Murti Bhavan",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Teen_Murti_Bhavan_Building_complex_in_Delhi.jpg",
            "official_description": "The Teen Murti Bhavan is the former residence of the first Prime Minister of India, Jawaharlal Nehru in Delhi, India, who stayed here for 16 years until his death on May 27, 1964. It was designed by Robert Tor Russell, the British architect of Connaught Place and of the Eastern and Western Courts on Janpath during the British Raj. Teen Murti Bhavan was built in 1930 as part of the new imperial capital of India, New Delhi as the residence of the Commander-in-Chief of the British Indian Army.",
            "location": "Delhi",
            "latitude": 28369.39,
            "longitude": 771155.58,
            "pincode": "110011"
        },
        {
            "id": 58,
            "name": "Tannirbhavi Beach",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "Tannirbhavi beach is a beach in Mangalore, Karnataka, India. Currently, it can only be reached by land near Kuloor Bridge or by ferry via Gurupura river from Sultan Battery.",
            "location": "Mangalore",
            "latitude": 12.891302,
            "longitude": 74.813874,
            "pincode": "575001"
        },
        {
            "id": 32,
            "name": "Talakona Waterfall",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "The Temple at Talakona water falls is a Siva Temple known as \"SIDDHESWARA SWAMY TEMPLE\". The diety is called as 'Siddheswara'.",
            "location": "Tirupathi",
            "latitude": 23.023367,
            "longitude": 88.10528,
            "pincode": " 08584"
        },
        {
            "id": 43,
            "name": "Solang Valley",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Solang Nala (Valley) drives its name from combination of words Solang (Nearby village) and Nullah (water stream). It is a side valley at the top of the Kullu Valley in Himachal Pradesh, India 14 km northwest of the resort town Manali on the way to Rohtang Pass, and is known for its summer and winter sport conditions. The sports most commonly offered are parachuting, paragliding, skating and zorbing.",
            "location": "Manali",
            "latitude": 32.313106,
            "longitude": 77.163535,
            "pincode": "175131"
        },
        {
            "id": 50,
            "name": "Shimla Glen",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "The Most Beautiful waterfalls in the north india.",
            "location": "Shimla",
            "latitude": 30.354561,
            "longitude": 77.818064,
            "pincode": "171001"
        },
        {
            "id": 53,
            "name": "Shanti Stupa",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "Shanti Stupa is a Buddhist white-domed stupa on a hilltop in Chanspa, Leh district, Ladakh, in the north Indian state of Jammu and Kashmir. It was built in 1991 by Japanese Buddhist Bhikshu, Gyomyo Nakamura and part of the Peace Pagoda mission. ",
            "location": "Leh",
            "latitude": 34.176545,
            "longitude": 77.578944,
            "pincode": "194101"
        },
        {
            "id": 79,
            "name": "Shani Dham Temple",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/250px-Shanidham-1.jpg",
            "official_description": "Shani Dham Temple is located in the Indian capital of Delhi and contains the world's tallest statue of Shani.\r\n\r\nIn the last few years i.e. on May31, 2003 the largest Shani Idol was unveiled by Anant Shree Vibhushit Jagat Guru Shankracharya Swami Madhavasharam Ji Maharaj. Since then, it has become an attraction for the devotees of Lord Shani. Before unveiling the idol of Shani, Shree Shani Dham Peethadeshwar Sant Shiromani Shani Charanuragi 'Datti' Madan Maharaj Rajasthani Ji performed the enchanting of One Hundred Crores, and Thirty Two Lakhs Shani Mantras on the sacred grove.",
            "location": "Delhi",
            "latitude": 0,
            "longitude": 0,
            "pincode": "110085"
        },
        {
            "id": 87,
            "name": "Satpula",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/APP3.jpg",
            "official_description": "Satpula is a remarkable ancient water harvesting dam or weir located about 800 m east of the Khirki Masjid that is integral to the compound wall of the medieval fourth city of the Jahanpanah in Delhi, with its construction credited to the reign of Sultan Muhammad Shah Tughlaq of the Tughlaq Dynasty.",
            "location": "Delhi",
            "latitude": 283154.23,
            "longitude": 771324.61,
            "pincode": "110013"
        },
        {
            "id": 18,
            "name": "Rushikonda Beach",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Located along the coast of Vizag, Rama Krishna Beach is known for its pristine sands and crystal clear waters of the Bay of Bengal. It is adjoining the Lawson's Bay Beach and offers awe-inspiring natural views and vistas. The beach is perfect for catching mesmerising sunsets and sunrises.",
            "location": "Visakapatanam",
            "latitude": 17.778339,
            "longitude": 83.382176,
            "pincode": "530045"
        },
        {
            "id": 86,
            "name": "Roshanara Bagh",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Roshanara-Bagh.jpg",
            "official_description": "Roshanara Garden is a Mughal-style garden built by Roshanara Begum, the second daughter of the Mughal emperor Shah Jahan. It is situated in Shakti Nagar near Kamla Nagar Clock Tower and North Campus of the University of Delhi. It is one of the biggest gardens in Delhi having a great variety of plants, some imported from Japan. The lake inside the gardens is visited by migratory birds during winters and is a popular site for bird watching.\r\n",
            "location": "Delhi",
            "latitude": 284023,
            "longitude": 771152,
            "pincode": "110007"
        },
        {
            "id": 21,
            "name": "Red Fort",
            "type": 6,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/redfort1.jpg",
            "official_description": "The Red Fort was the residence of the Mughal emperor of India for nearly 200 years, until 1857. It is located in the centre of Delhi and houses a number of museums. In addition to accommodating the emperors and their households, it was the ceremonial and political centre of Mughal government and the setting for events critically impacting the region",
            "location": "Delhi",
            "latitude": 27.171466,
            "longitude": 78.018553,
            "pincode": "11000"
        },
        {
            "id": 49,
            "name": "Rashtrapati Niwas",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "The Rashtrapati Niwas, also known as Viceregal Lodge, is located on the Observatory Hills of Shimla, Himachal Pradesh, India. It was formerly the residence of the British Viceroy of India.",
            "location": "Shimla",
            "latitude": 31.104814,
            "longitude": 77.173403,
            "pincode": "171001"
        },
        {
            "id": 68,
            "name": "Rashtrapati Bhavan",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/1280px-RASHTRAPATI_BHAVAN.jpg",
            "official_description": "The Rashtrapati Bhavan, \"Presidential Residence\" is the official home of the President of India, located in New Delhi, India. It may refer to only the mansion that has the President's official residence, halls, guest rooms and offices; it may also refer to the entire 130 hectare President Estate that additionally includes huge presidential gardens, large open spaces, residences of bodyguards and staff, stables, other offices and utilities within its perimeter walls. The main palace building was formerly known as Viceroy's House. In terms of area, was the largest residence of a Head of State in the world until the Presidential Complex of Turkey opened 29 October 2014.",
            "location": "Delhi",
            "latitude": 283651.63,
            "longitude": 771159.29,
            "pincode": "110004"
        },
        {
            "id": 66,
            "name": "Qutb Minar",
            "type": 6,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/941FB8D61E1F48D4B618028E73825E70.jpg",
            "official_description": "Qutub Minar, at 120 meters, is the tallest brick minaret in the world, and the second tallest Minar in India after Fateh Burj at Mohali. Qutub Minar, along with the ancient and medieval monuments surrounding it, from the Qutb Complex, which is a UNESCO World Heritage Site. The tower is located in the Mehrauli area of Delhi, India. Made of red sandstone and marble, Qutub Minar is a 72.5-meter tall tapering tower with a diameter measuring 14.32 meters at the base and 2.75 meters at the peak. Inside the tower, a circular staircase with 379 steps leads to the top. Qutub Minar station is the closest station on the Delhi Metro.\r\n",
            "location": "Delhi",
            "latitude": 283128,
            "longitude": 771107,
            "pincode": "110030"
        },
        {
            "id": 74,
            "name": "Qutb complex",
            "type": 6,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/300px-Qutb_minar_ruins.jpg",
            "official_description": "The Qutb complex  also spelled Qutab or Qutub, is an array of monuments and buildings at Mehrauli in Delhi, India. The best-known structure in the complex is the Qutb Minar, built to honor the Sufi saint Qutbuddin Bakhtiar Kaki. Its foundation was laid by Qutbud-din Aibak, who later became the first Sultan of Delhi of the Mamluk dynasty. The Minar was added upon by his successor Iltutmish, and much later by Firoz Shah Tughlaq, a Sultan of Delhi from the Tughlaq dynasty in 1368 AD. The Qubbatul-Islam Mosque, later corrupted into Quwwat-ul Islam stands next to the Qutb Minar. It was built on the ruins of Lal Kot Fort and Qila-Rai-Pithora, whom Ghori's Afghan armies had earlier defeated and killed in the Second Battle of Tarain.",
            "location": "Delhi",
            "latitude": 283127.77,
            "longitude": 77117.55,
            "pincode": "110030"
        },
        {
            "id": 85,
            "name": "Okhla Sanctuary",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Northern_Shoveler_6895200091.jpg",
            "official_description": "Okhla Bird Sanctuary is a bird sanctuary at the Okhla barrage over Yamuna River. It is situated in Noida, Gautam Buddh Nagar district, on Delhi-Uttar Pradesh state border and known as a haven for over 300 bird species, especially waterbirds. In 1990, an area of 3.5 square kilometres on the river Yamuna was designated a bird sanctuary by the Government of Uttar Pradesh under the Wildlife Protection Act, 1972. The site is located at the point where the river enters Uttar Pradesh. The most prominent feature of the sanctuary is the large lake created by damming the river, which lies between Okhla village to the west and Gautam Budh Nagar to the east. The Okhla Bird Sanctuary is roughly 4 square kilometres in size and is situated at the entrance of NOIDA in Gautam Budh Nagar district of Uttar Pradesh. It is situated at a point where river Yamuna enters in the state of Uttar Pradesh leaving the territory of Delhi. It is one among fifteen bird sanctuaries in the state.",
            "location": "Delhi",
            "latitude": 283354,
            "longitude": 771810.8,
            "pincode": "110020"
        },
        {
            "id": 56,
            "name": "Nishat Bagh",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "Nishat Bagh is a terraced Mughal garden built on the eastern side of the Dal Lake, close to Srinagar in the state of Jammu and Kashmir, India. It is the second largest Mughal garden in the Kashmir Valley.",
            "location": "Srinagar",
            "latitude": 30.321651,
            "longitude": 76.853358,
            "pincode": "190001"
        },
        {
            "id": 33,
            "name": "Natural Arch, Tirumala hills",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Natural Arch, Tirumala hills is a distinctive geological wonder located 1 km (0.6 mi) North of the Tirumala hills temple, near the Chakra Teertham in the state of Andhra Pradesh, India. The Arch is also called Silathoranam (శిలాతోరణం)in local language (Telugu language: “Sila” means ‘rock’ and “thoranam” means a garland strung over a threshold, connecting two vertical columns or an ‘arch’ as in this case)",
            "location": "Tirupathi",
            "latitude": 19.43814,
            "longitude": 72.822791,
            "pincode": " 517 5"
        },
        {
            "id": 77,
            "name": "National Zoological Park Delhi",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/National-Zoological-Park-Delhi.jpg",
            "official_description": "The National Zoological Park is a 176-acre zoo near the Old Fort in Delhi, India. A 16th-century citadel, a sprawling green island and a motley collection of animals and birds, all in the middle of a burgeoning urban Delhi. The zoo is home to about 1350 animals representing almost 130 species of animals and birds from around the world. Currently, the director of the zoo is Shri Amitabh Agnihotri, IFS. The zoo can be seen on foot or using a battery-operated vehicle which can be rented at the zoo. Visitors are not permitted to bring any food other than drinking water, but there is a canteen in the zoo. In 2014 a visitor was killed as he had fallen into the white tigers enclosure, leading to questions about visitor and animal safety at the zoo.",
            "location": "Delhi",
            "latitude": 283615.97,
            "longitude": 771446.31,
            "pincode": "110003"
        },
        {
            "id": 75,
            "name": "National Museum, New Delhi",
            "type": 3,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/National-Museum-Delhi.jpg",
            "official_description": "The National Museum in New Delhi is one of the largest museums in India. Established in 1949, it holds  the variety of articles ranging from pre-historic era to modern works of art. It functions under the Ministry of Culture, Government of India. The museum is situated on the corner of Janpath and Maulana Azad Road. The blue–print of the National Museum had been prepared by the Gwyer Committee set up by the Government of India in 1946. The Museum has around 200,000 works of art, both of Indian and foreign origin, covering over 5,000 years. It remains closed on Mondays",
            "location": "Delhi",
            "latitude": 283642.52,
            "longitude": 77139.34,
            "pincode": "110011"
        },
        {
            "id": 29,
            "name": "Mollem National park",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Mollem National Park is a 240 square kilometres (93 sq mi) protected area located in the Western Ghats of South India, in Sanguem taluk, Goa along the eastern border with Karnataka. The area is situated near the town of Molem, 57 kilometres (35 mi) east of Panaji, the state capital of Goa. National Highway 4A divides it into two parts and the Mormugao - Londa railway line passes through the area.",
            "location": "Goa",
            "latitude": 15.333901,
            "longitude": 74.288354,
            "pincode": "403410"
        },
        {
            "id": 7,
            "name": "Marine Drive",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/annual-report-old.jpg",
            "official_description": "Marine Drive is a 4.3-kilometre-long boulevard in South Mumbai in the city of Mumbai. It is a 'C'-shaped six-lane concrete road along the coast, which is a natural bay. The road links Nariman Point to Babulnath and Malabar Hill. Marine Drive is situated over reclaimed land facing west-south-west.",
            "location": "Mumbai",
            "latitude": 18.944,
            "longitude": 72.823,
            "pincode": "400002"
        },
        {
            "id": 28,
            "name": "Mangueshi Temple",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Shri Mangeshi temple (Devanagari: श्री मंगेशी मंदीर) is located at Mangeshi Village in Priol, Ponda taluk, Goa.It is at a distance of 1 km from Mardol close to Nagueshi, 21 km from Panaji the capital of Goa, and 26 km from Margao.This temple is one of the largest and most frequently visited temples in Goa.In 2011, the temple along with others in the area instituted a dress code on visitors of the temple.\r\n",
            "location": "Goa",
            "latitude": 15.260473,
            "longitude": 73.975926,
            "pincode": " 40300"
        },
        {
            "id": 51,
            "name": "Magnetic Hill",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "Magnet Hill is a so-called \"gravity hill\" located near Leh in Ladakh, India.",
            "location": "Leh",
            "latitude": 34.174335,
            "longitude": 77.354522,
            "pincode": "194101"
        },
        {
            "id": 64,
            "name": "Lotus Temple",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Lotus-Temple-8.jpg",
            "official_description": "The Lotus Temple, located in New Delhi, India, is a Bahá'í House of Worship completed in 1986. Notable for its flowerlike shape, it serves as the Mother Temple of the Indian subcontinent and has become a prominent attraction in the city. The Lotus Temple has won numerous architectural awards and been featured in hundreds of newspaper and magazine articles.",
            "location": "Delhi",
            "latitude": 28.553325,
            "longitude": 77.2586,
            "pincode": "110019"
        },
        {
            "id": 22,
            "name": "Lotus Temple",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "The Lotus Temple, located in New Delhi, India, is a Bahá'í House of Worship completed in 1986. Notable for its flowerlike shape, it serves as the Mother Temple of the Indian subcontinent and has become a prominent attraction in the city.",
            "location": "Delhi",
            "latitude": 28.552409,
            "longitude": 77.260113,
            "pincode": "110001"
        },
        {
            "id": 73,
            "name": "Lodi Gardens",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Lodi-Garden.jpg",
            "official_description": "Lodhi Gardens is a city park situated in New Delhi, India. Spread over 90 acres, it contains, Mohammed Shah's Tomb, Tomb of Sikandar Lodi, Shisha Gumbad and Bara Gumbad, architectural works of the 15th century by Lodhis who ruled parts of northern India and Punjab and Khyber Pakhtunkhwa province of modern-day Pakistan, from 1451 to 1526. The site is now protected by the Archaeological Survey of India.",
            "location": "Delhi",
            "latitude": 283534.8,
            "longitude": 771312,
            "pincode": "110003"
        },
        {
            "id": 9,
            "name": "Lal Bagh",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/800px-Lalbagh_Glasshouse_night_panorama.jpg",
            "official_description": "Bangalore is one of the most important tourist centers of the Karnataka state. Central business district of Bangalore consists of places MG Road, Brigade Road, Commercial Street, Vidhana Soudha etc. Bangalore has many lakes and parks.",
            "location": "Bangalore",
            "latitude": 12.95,
            "longitude": 77.59,
            "pincode": "560004"
        },
        {
            "id": 42,
            "name": "Kareri Lake",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Kareri Lake is a high altitude, shallow, fresh water lake south of the Dhauladhar range approximately 9 km North West of Dharamsala in Kangra district, Himachal Pradesh. Its surface is 2934 metres above the sea level.",
            "location": "Dharamsala ",
            "latitude": 32.325704,
            "longitude": 76.273436,
            "pincode": " 17621"
        },
        {
            "id": 36,
            "name": "Kankaria",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Kankaria Lake is the biggest lake in Ahmedabad in the state of Gujarat, India. It is located in the southern part of the city, in the Maninagar area. A lakefront has been developed around it, which has many public attractions such as a zoo, toy train, kids city, tethered balloon ride, water rides, water park, food stalls, and entertainment facilities. The lakefront was revamped in 2008. Kankaria Carnival is a week-long festival held here in the last week of December. Many cultural, art, and social activities are organised during the carnival.",
            "location": "Ahmedabad",
            "latitude": 23.006257,
            "longitude": 72.60255,
            "pincode": "380008"
        },
        {
            "id": 38,
            "name": "Kangra Valley",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Kangra Valley is situated in Himachal Pradesh, India. It is a popular tourist destination, with the peak season around March and April. The Kangri language is spoken there.",
            "location": "Dharamsala ",
            "latitude": 32.166667,
            "longitude": 76.5,
            "pincode": " 17621"
        },
        {
            "id": 16,
            "name": "Kailasagiri",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Kailasagiri is a hilltop park in the city of Visakhapatnam.The park was developed by Visakhapatnam Urban Development Authority (VUDA) comprising 380 acres (150 ha) of land covered with flora and tropical trees. The hill, at 360 feet (110 m), overlooks beaches, forests, and the city of Visakhapatnam.",
            "location": "Visakapatanam",
            "latitude": 17.749884,
            "longitude": 83.340197,
            "pincode": "530001"
        },
        {
            "id": 59,
            "name": "Kadri Manjunath Temple",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "Kadri Manjunatha Temple is located in Mangalore in the state of Karnataka, India, was originally made by Vajrayana Buddhist but later on due to fall of Buddhism converted for the deity Manjunatha by Hindus.",
            "location": "Mangalore",
            "latitude": 12.879049,
            "longitude": 74.853219,
            "pincode": "575001"
        },
        {
            "id": 8,
            "name": "Juhu Beach",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Juhu_beach_Arial.jpg",
            "official_description": "Juhu is a suburb of Mumbai. It is most famous for the sprawling Juhu beach. It surrounded by the Arabian Sea to the west, Versova to the north, Santacruz and Vile Parle to the east, and Khar to the south. Juhu is among the most affluent areas of the city and home to many Bollywood celebrities.",
            "location": "Mumbai",
            "latitude": 19.1,
            "longitude": 72.83,
            "pincode": "400049"
        },
        {
            "id": 71,
            "name": "Jantar Mantar, New Delhi",
            "type": 6,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/300px-Jantar_Mantar_Delhi_27-05-2005.jpg",
            "official_description": "The Jantar Mantar is located in the modern city of New Delhi. It consists of 13 architectural astronomy instruments. The site is one of five built by Maharaja Jai Singh II of Jaipur, from 1723 onwards, as he was given by Mughal emperor Muhammad Shah the task of revising the calendar and astronomical tables. There is a plaque fixed on one of the structures in the Jantar Mantar observatory in New Delhi that was placed there in 1910 mistakenly dating the construction of the complex to the year 1710. Later research, though, suggests 1724 as the actual year of construction.\r\n\r\nThe primary purpose of the observatory was to compile astronomical tables and to predict the times and movements of the sun, moon and planets. Some of these purposes nowadays would be classified as astronomy.\r\n\r\nCompleted in 1724, the Delhi Jantar Mantar had decayed considerably by 1867.",
            "location": "Delhi",
            "latitude": 283737.59,
            "longitude": 771259.32,
            "pincode": "110001"
        },
        {
            "id": 54,
            "name": "Jamia Masjid",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "Jamia Masjid is a mosque in Srinagar, Jammu & Kashmir, India. The Jamia Masjid of Srinagar is situated at Nowhatta, in the middle of the old city.",
            "location": "Srinagar",
            "latitude": 16.203804,
            "longitude": 77.349326,
            "pincode": "190001"
        },
        {
            "id": 34,
            "name": "Jama Masjid",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Jama Masjid (literally Friday Mosque), also known as Jami or Jumma Mosque, is the most splendid mosque of Ahmedabad, built in 1424 during the reign of Ahmed Shah I. Lying in the old walled city, the mosque is situated outside Bhadra Fort area, along the south side of the road extending from Teen Darwaza to Manek Chowk.",
            "location": "Ahmedabad",
            "latitude": 28.651613,
            "longitude": 77.235486,
            "pincode": "380001"
        },
        {
            "id": 67,
            "name": "Jama Masjid",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/new-delhi--2106102-3.jpg",
            "official_description": "The Masjid-i Jahān-Numā, commonly known as the Jama Masjid of Delhi, is one of the largest mosques in India.",
            "location": "Delhi",
            "latitude": 28.6507,
            "longitude": 77.2334,
            "pincode": "110006"
        },
        {
            "id": 81,
            "name": "ISKCON Temple Delhi",
            "type": 3,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/isckon-temple.jpg",
            "official_description": "Sri Sri Radha Parthasarathi Mandir, generally known as the ISKCON Delhi temple, is a well known Vaishnav temple of Lord Krishna and Radharani in the form of Radha Parthasarathi. Opened in 1998, it is located at Hare Krishna Hills, in the East of Kailash area of New Delhi, India.It is one of the top tourist place in Delhi to visit.It is not just a temple but also a Vedic Learning Center in very scientific way.",
            "location": "Delhi",
            "latitude": 283329,
            "longitude": 771436,
            "pincode": "110065"
        },
        {
            "id": 95,
            "name": "ISKCON Temple Bangalore",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/240px-ISKCON_Banglaore_Temple.jpg",
            "official_description": "Sri Radha Krishna Temple has deities of Radha and Krishna located at Rajajinagar, in North Bangalore, Karnataka, India. It is one of the largest ISKCON temples in the world. The temple is a huge cultural complex that was inaugurated in 1997 by Shankar Dayal Sharma. The project was conceived and executed by Madhu Pandit Dasa following the wishes of HDG A. C. Bhaktivedanta Swami Prabhupada, the Founder-Acarya of ISKCON to promote Vedic culture and spiritual learning.",
            "location": "bengaluru",
            "latitude": 13034,
            "longitude": 77333,
            "pincode": "560020"
        },
        {
            "id": 25,
            "name": "ISKCON Temple",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Sri Sri Radha Parthasarathi Mandir, generally known as the ISKCON Delhi temple, is a well known Vaishnav temple of Lord Krishna and Radharani in the form of Radha Parthasarathi.",
            "location": "Delhi",
            "latitude": 28.613939,
            "longitude": 77.209021,
            "pincode": "110014"
        },
        {
            "id": 70,
            "name": "Iron pillar of Delhi",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Iron-Pillar-Pictures.jpg",
            "official_description": "The Iron Pillar located in Delhi, India, is a 7 m column in the Qutb complex, notable for the rust-resistant composition of the metals used in its construction. The pillar has attracted the attention of archaeologists and materials scientists and has been called \"a testament to the skill of ancient Indian blacksmiths\" because of its high resistance to corrosion. The corrosion resistance results from an even layer of crystalline iron hydrogen phosphate forming on the high phosphorus content iron, which serves to protect it from the effects of the local Delhi climate",
            "location": "Delhi",
            "latitude": 283128.76,
            "longitude": 77116.25,
            "pincode": "110044"
        },
        {
            "id": 19,
            "name": "Indira Gandhi Zoological Park",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "This Zoological Park is named after The Former Prime Minister Of India, Mrs. Indira Gandhi. It was declared open to the public on 19 May 1977. It covers an area of 625 acres (253 ha). It is situated in Visakhapatnam amidst the scenic Eastern Ghats of India. It is surrounded by Eastern Ghats on three sides and Bay of Bengal on the fourth side. Nearly eighty species of animals numbering to about eight hundred are present in the zoo.",
            "location": "Visakapatanam",
            "latitude": 17.767295,
            "longitude": 83.348974,
            "pincode": "530043"
        },
        {
            "id": 65,
            "name": "India Gate",
            "type": 6,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/india-gate.jpg",
            "official_description": "The India Gate  is a war memorial located astride the Rajpath, on the eastern edge of the ‘ceremonial axis’ of New Delhi, formerly called Kingsway. India gate is a memorial to 82,000 soldiers of the undivided Indian Army who died in the period 1914–21 in the First World War, in France, Flanders, Mesopotamia, Persia, East Africa, Gallipoli and elsewhere in the Near and the Far East, and the Third Anglo-Afghan War. 13,300 servicemen's names, including some soldiers and officers from the United Kingdom, are inscribed on the gate. The India Gate, even though a war memorial, evokes the architectural style of the triumphal arch-like the Arch of Constantine, outside the Colosseum in Rome, and is often compared to the Arc de Triomphe in Paris, and the Gateway of India in Mumbai. It was designed by Sir Edwin Lutyens.",
            "location": "Delhi",
            "latitude": 283646.31,
            "longitude": 771345.5,
            "pincode": "110006"
        },
        {
            "id": 24,
            "name": "India Gate",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "The India Gate, (originally called the All India War Memorial), is a war memorial located astride the Rajpath, on the eastern edge of the ‘ceremonial axis’ of New Delhi, formerly called Kingsway. India gate is a memorial to 82,000 soldiers of the undivided Indian Army who died in the period 1914–21 in the First World War, in France, Flanders, Mesopotamia, Persia, East Africa, Gallipoli and elsewhere in the Near and the Far East, and the Third Anglo-Afghan War. 13,300 servicemen's names, including some soldiers and officers from the United Kingdom, are inscribed on the gate.",
            "location": "Delhi",
            "latitude": 28.61094,
            "longitude": 77.234482,
            "pincode": "110006"
        },
        {
            "id": 80,
            "name": "Hijron Ka Khanqah",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/eazq_3700765205_622fab67a5_b.jpg",
            "official_description": "Hijron Ka Khanqah is an Islamic monument located in Mehrauli, South Delhi, India. The literal meaning of Hijron ka Khanqah is a “Sufi spiritual retreat for eunuchs”. It is one of the many monuments located in the Mehrauli village within the Archeological Park. It is maintained well by the Hijras of Turkman Gate, in Shahjahanabad who are in possession of this 15th-century monument since the 20th century.",
            "location": "Delhi",
            "latitude": 283119,
            "longitude": 771043,
            "pincode": "110001"
        },
        {
            "id": 44,
            "name": "Hidimba Devi Temple",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Hidimbi Devi Temple, also known variously as the Hadimba Temple, is located in Manāli, a hill station in the State of Himāchal Pradesh in north India.",
            "location": "Manali",
            "latitude": 31.919139,
            "longitude": 75.857866,
            "pincode": "175131"
        },
        {
            "id": 88,
            "name": "Hauz-i-Shamsi",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Tower_at_the_location_of_prophets_horses_hoop.jpg",
            "official_description": "Hauz-i-Shamsi is a water storage reservoir or tank built by Iltutmish of the Slave Dynasty in 1230 CE, at a location revealed to him in a dream by the Islamic prophet Muhammad. A palace called the Jahaz Mahal was built on the eastern edge of the same reservoir during the Lodi dynasty period in the 16th century as a retreat or Inn for use by pilgrims. Also at the edge of Hauz is the tomb of 17th century Persian writer in the Mughal court, Abdul-Haqq Dehlavi. The monuments are situated in Mehrauli, Delhi.",
            "location": "Delhi",
            "latitude": 283051,
            "longitude": 771042,
            "pincode": "110032"
        },
        {
            "id": 57,
            "name": "Hari Parbat",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "Hari Parbat, locally known as Koh-e-Maran, is a hill overlooking Srinagar, the largest city and summer capital of Jammu and Kashmir.",
            "location": "Srinagar",
            "latitude": 34.107455,
            "longitude": 74.816351,
            "pincode": "190001"
        },
        {
            "id": 6,
            "name": "Hanging Garden",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Hanging-Gardens-4.jpg",
            "official_description": "The Hanging Gardens, in Mumbai, also known as Pherozeshah Mehta Gardens, are terraced gardens perched at the top of Malabar Hill, on its western side, just opposite the Kamala Nehru Park. They provide sunset views over the Arabian Sea and feature numerous hedges carved into the shapes of animals",
            "location": "Mumbai",
            "latitude": 18.956724,
            "longitude": 72.803937,
            "pincode": "400006"
        },
        {
            "id": 13,
            "name": "HAL Aerospace Museum",
            "type": 3,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/800px-HAL_heritage_centre_and_aerospace_museum_bangalore_7641.JPG",
            "official_description": "HAL Aerospace Museum is India's first aerospace museum located at Hindustan Aeronautics Limited premises, in Bangalore. Established in 2001, the Museum is part of the HAL Heritage Centre and Aero Space Museum, and showcases the growth of the Indian aviation industry and HAL for six decades.",
            "location": "Bangalore",
            "latitude": 12.955431,
            "longitude": 77.681386,
            "pincode": "560075"
        },
        {
            "id": 72,
            "name": "Gurudwara Bangla Sahib",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Bangla_Sahib-14.jpg",
            "official_description": "Gurudwara Bangla Sahib; is one of the most prominent Sikh gurdwara, or Sikh house of worship, in Delhi, India and known for its association with the eighth Sikh Guru, Guru Har Krishan, as well as the pool inside its complex, known as the \"Sarovar.\" It was first built as a small temple by Sikh General Sardar Bhagel Singh in 1783, who supervised the construction of nine Sikh shrines in Delhi in the same year, during the reign of Mughal Emperor, Shah Alam II.",
            "location": "Delhi",
            "latitude": 283736.12,
            "longitude": 771232.04,
            "pincode": "110001"
        },
        {
            "id": 46,
            "name": "Great Himalayan National Park",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "The Great Himalayan National Park, is one of India's national parks, is located in Kullu region in the state of Himachal Pradesh. The park was established in 1984 and is spread over an area of 1,171 km² at an altitude of between 1500 to 6000 m.",
            "location": "Manali",
            "latitude": 31.802412,
            "longitude": 77.69942,
            "pincode": "175131"
        },
        {
            "id": 14,
            "name": "Government Museum (Bangalore)",
            "type": 3,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/800px-Government_Museum_Banglore_305.jpg",
            "official_description": "Government Museum (Bangalore) established in 1865 by the Mysore State with the guidance of Surgeon Edward Balfour who founded the museum in Madras and supported by the Chief Commissioner of Mysore, L.B. Bowring is one of the oldest museums in India and the second oldest museum in South India.It is now an archaeological museum and has a rare collection of archaeological and geological artifacts including old jewellery, sculpture, coins and inscriptions.",
            "location": "Bangalore",
            "latitude": 12.9747255,
            "longitude": 77.594769,
            "pincode": "560025"
        },
        {
            "id": 99,
            "name": "Gateway of India",
            "type": 6,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/2015-08-14_IndiaIndependenceDay_EN-IN10167493544_1920x1080.jpg",
            "official_description": "The Gateway of India is a monument built during the 20th century in Mumbai City of Maharashtra state in Western India. It is located on the waterfront in the Apollo Bunder area in South Mumbai and overlooks the Arabian Sea. The structure is a basalt arch, 26 metres high. It lies at the end of Chhatrapati Shivaji Marg at the water's edge in Mumbai Harbour. It was a crude jetty used by the fishing community which was later renovated and used as a landing place for British governors and other prominent people. In earlier times, it would have been the first structure that visitors arriving by boat in Mumbai would have seen. The Gateway has also been referred to as the Taj Mahal of Mumbai, and is the city's top tourist attraction. The India Gate in New Delhi is similar to the Gateway of India in Mumbai. The structure was erected to commemorate the landing of King George V and Queen Mary at Apollo Bunder, when they visited India in 1911. Built in Indo-Saracenic style, the foundation stone for the Gateway of India was laid on 31 March 1911. The final design of George Wittet was sanctioned in 1914 and the construction of the monument was completed in 1924. The Gateway was later the ceremonial entrance to India for Viceroys and the new Governors of Bombay. It served to allow entry and access to India.",
            "location": "Mumbai",
            "latitude": 185518.84,
            "longitude": 72504.56,
            "pincode": "400039"
        },
        {
            "id": 83,
            "name": "Garden of Five Senses",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Garden-of-Five-Senses.jpg",
            "official_description": "The Garden of Five Senses is a park spread over 20 acres, in Saidul Ajaib village, opposite Saket, near the Mehrauli heritage area in Delhi, India. Designed by Delhi architect, Pradeep Sachdeva, the park was developed by Delhi Tourism and Transportation Development Corporation, Delhi at a cost of Rs 10.5 crore, over a period of three years and opened in February 2003. Partly built over a rocky terrain, the garden has various theme areas, including a section on the lines of Mughal Gardens, plus pools of water lilies, bamboo courts, herb gardens and solar energy park.\r\n",
            "location": "Delhi",
            "latitude": 283048.03,
            "longitude": 771152.78,
            "pincode": "110030"
        },
        {
            "id": 27,
            "name": "Fort Aguada",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "The fort was constructed in 1612 to guard against the Dutch and the Marathas. It was a reference point for the vessels coming from Europe at that time. This old Portuguese fort stands on the beach south of Candolim, at the shore of the Mandovi River. It was initially tasked with defense of shipping and the nearby Bardez sub district.",
            "location": "Goa",
            "latitude": 15.512823,
            "longitude": 73.768867,
            "pincode": "403515"
        },
        {
            "id": 30,
            "name": "Dudhsagar Waterfalls",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/dudsagar-waterfalls.jpg",
            "official_description": "Dudhsagar Falls is a four-tiered waterfall located on the Mandovi River in the Indian state of Goa. It is 60 km from Panaji by road and is located on the Madgaon-Belgaum rail route about 46 km east of Madgaon and 80 km south of Belgaum.",
            "location": "Goa",
            "latitude": 15.314469,
            "longitude": 74.314067,
            "pincode": " 40310"
        },
        {
            "id": 55,
            "name": "Dal Lake",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "Dal Lake is a lake in Srinagar, the summer capital of Jammu and Kashmir. The urban lake, which is the second largest in the state, is integral to tourism and recreation in Kashmir.",
            "location": "Srinagar",
            "latitude": 34.110586,
            "longitude": 74.868257,
            "pincode": "190001"
        },
        {
            "id": 41,
            "name": "Dal Lake",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Dal Lake is a small mid-altitude lake near the village of Tota Rani in Kangra district (Himachal Pradesh) in northern India. The name 'Dal Lake' is taken from Kashmir's Dal Lake.",
            "location": "Dharamsala ",
            "latitude": 34.110586,
            "longitude": 74.868257,
            "pincode": " 17621"
        },
        {
            "id": 93,
            "name": "Cubbon Park",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/518251727_1acf970ce7_z.jpg",
            "official_description": "Cubbon Park is a landmark 'lung' area of the Bangalore city, located within the heart of city in the Central Administrative Area. Originally created in 1870, when Major General Richard Sankey was the then British Chief Engineer of Mysore state, it covered an area of 100 acres and subsequent expansion has taken place and the area reported now is about 300 acres. It has a rich recorded history of abundant flora and fauna plantations coupled with numerous impressive and aesthetically located buildings and statues of famous personages, in its precincts. This public park was first named as “Meade’s Park” after Sir John Meade, the acting Commissioner of Mysore in 1870 and subsequently renamed as Cubbon Park after the longest serving commissioner of the time, Sir Mark Cubbon. To commemorate the Silver Jubilee of Sri Krishnaraja Wodeyar’s rule in Mysore State, in the year 1927, the park was again renamed as \"Sri. Chamarajendra Park\", in memory of the 19th Century ruler of the state Sri Chamarajendra Wodeyar during whose rule the park came into existence. The landscaping in the park creatively integrates natural rock outcrops with thickets of trees, massive bamboos, with grassy expanse and flowerbeds and the monuments within its limits, regulated by the Horticulture Department of the Government of Karnataka. The predominantly green area of the park has many motorable roads, and the well laid out walking paths running through the park are frequented by early morning walkers and the naturalists who study plants in the tranquil natural environment.",
            "location": "bengaluru",
            "latitude": 125812,
            "longitude": 77360,
            "pincode": "560001"
        },
        {
            "id": 10,
            "name": "Cubbon Park",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/800px-Cubbon_Park_W.jpg",
            "official_description": "Cubbon Park is a landmark 'lung' area of the Bangalore city, located within the heart of city in the Central Administrative Area. Originally created in 1870, when Major General Richard Sankey was the then British Chief Engineer of Mysore state, it covered an area of 100 acres (0.40 km2) and subsequent expansion has taken place and the area reported now is about 300 acres (1.2 km2).[1] It has a rich recorded history of abundant flora and fauna plantations coupled with numerous impressive and aesthetically located buildings and statues of famous personages, in its precincts.",
            "location": "Bangalore",
            "latitude": 12.97,
            "longitude": 77.6,
            "pincode": "560001"
        },
        {
            "id": 84,
            "name": "Coronation Park, Delhi",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Coronation_Park_Delhi_28.JPG",
            "official_description": "Coronation Park is a park located on Burari Road near Nirankari Sarovar in Delhi, India. The park is sometimes referred to as the Coronation Memorial; it was the venue of the Delhi Durbar of 1877 when Queen Victoria was proclaimed the Empress of India. Later it was used to celebrate the accession of King Edward VII in 1903, and, finally, it was here that the Durbar commemorating the coronation of King George V as Emperor of India took place on 12 December 1911, subsequent to his coronation at Westminster Abbey in June 1911. This last celebration had all the princely states in attendance. The decision to hold the Coronation Durbars in Delhi at the vast open ground at Coronation Park was a move to emphasise Delhi's history.\r\n",
            "location": "Delhi",
            "latitude": 284322.82,
            "longitude": 771148.81,
            "pincode": "110002"
        },
        {
            "id": 48,
            "name": "Christ Church Shimla",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "Christ Church, Shimla, is the second oldest church in North India, after St John's Church in Meerut. It is a parish in the Diocese of Amritsar in the Church of North India.",
            "location": "Shimla",
            "latitude": 18.97029,
            "longitude": 72.831724,
            "pincode": "171001"
        },
        {
            "id": 69,
            "name": "Chandni Chowk",
            "type": 5,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/634925701249119593_33.jpg",
            "official_description": "Chandni Chowk is one of the oldest and busiest markets in Old Delhi, India. Chandni Chowk is located close to Old Delhi Railway Station. The Red Fort monument is located within the market. It was built in the 17th century by Mughal Emperor of India Shah Jahan and designed by his daughter Jahan Ara. The market was once divided by canals to reflect moonlight and remains one of India's largest wholesale markets.\r\n",
            "location": "Delhi",
            "latitude": 28.656,
            "longitude": 77.231,
            "pincode": "110006"
        },
        {
            "id": 37,
            "name": "Calico Museum of Textiles",
            "type": 3,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "The Calico Museum of Textiles is located in the city of Ahmedabad in the state of Gujarat in western India. The museum is managed by the Sarabhai Foundation.",
            "location": "Ahmedabad",
            "latitude": 23.011905,
            "longitude": 72.568804,
            "pincode": " 38000"
        },
        {
            "id": 15,
            "name": "Bugle Rock",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/images.jpg",
            "official_description": "Bugle Rock is a massive rock in the Basavanagudi area of South Bangalore, in the state of Karnataka. It is an abrupt rise above the ground of peninsular gneiss as the main rock formation and with an assessed age of about 3,000 million years. Bugle Rock has generated wide interest among the scientific community.",
            "location": "Bangalore",
            "latitude": 12.943,
            "longitude": 77.57,
            "pincode": "560004"
        },
        {
            "id": 60,
            "name": "Brindavan Gardens",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/download.jpeg",
            "official_description": "The Brindavana Gardens is a garden located in the state of Karnataka in India. It lies adjoining the Krishnarajasagara dam which is built across the river Kaveri. The work on laying out this garden was started in the year 1927 and completed in 1932. ",
            "location": "Mysore",
            "latitude": 12.879049,
            "longitude": 74.853219,
            "pincode": "522007"
        },
        {
            "id": 20,
            "name": "Borra Caves",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "These caves are located 1,400 metres above sea level in Visakhapatnam's Anantagiri area. The caves are famous for their beautiful stalagmite and stalactite formations. Borra Caves have both religious and historical significance. The locals flock to the caves to worship a Shivalinga and an idol of Kamadenu, the divine bovine goddess of Hindu mythology.",
            "location": "Visakapatanam",
            "latitude": 18.244941,
            "longitude": 83.031305,
            "pincode": " 53514"
        },
        {
            "id": 45,
            "name": "Bhrigu Lake",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Bhrigu Lake is a lake located at an elevation of around 4,300 metres in Kullu district, Himachal Pradesh, India. It is located to the east of Rohtang Pass and is around 6 kilometres from Gulaba village.",
            "location": "Manali",
            "latitude": 31.919139,
            "longitude": 75.857866,
            "pincode": "175131"
        },
        {
            "id": 40,
            "name": "Bhagsunag Falls",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Trail to Shri Gunna Devi Mandir, Dharamshala, Himachal Pradesh .",
            "location": "Dharamsala ",
            "latitude": 32.246735,
            "longitude": 76.336645,
            "pincode": " 17621"
        },
        {
            "id": 92,
            "name": "Bannerghatta National Park",
            "type": 1,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/j1.jpg",
            "official_description": "Bannerghatta National Park, near Bangalore, Karnataka, was founded in 1971 and declared as a national park in 1974. In 2002, a portion of the park, became a biological reserve, the Bannerghatta Biological Park. It is a popular tourist destination with a zoo, a pet corner, an animal rescue centre, a butterfly enclosure, an aquarium, a snake house and a safari park. There are ancient temples in the park for worship and it is a destination for trekking. The Zoo Authority of Karnataka, the University of Agricultural Sciences, Bangalore, and the Ashoka Trust for Research in Ecology and Environment are collaborating agencies. Within the national park area are six rural villages enclosed within three large enclosures for sheep and cattle farming",
            "location": "bengaluru",
            "latitude": 12483,
            "longitude": 773432,
            "pincode": "560083"
        },
        {
            "id": 11,
            "name": "Bangalore Palace",
            "type": 3,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/800px-Bangalore_palace.jpg",
            "official_description": "Bangalore Palace, a palace located in Bengaluru, Karnataka, India, was built by Rev. J. Garrett, who was the first Principal of the Central High School in Bangalore, now known as Central College.",
            "location": "Bangalore",
            "latitude": 12.998529,
            "longitude": 77.592103,
            "pincode": "560052"
        },
        {
            "id": 12,
            "name": "Bangalore Fort",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/800px-Old_Bangalore_Fort_Inside_View.JPG",
            "official_description": "Bangalore Fort began in 1537 as a mud fort.The builder was Kempe Gowda I, a vassal of the Vijaynagar Empire and the founder of Bangalore, now Bengaluru. Haider Ali in 1761 replaced the mud fort with a stone fort. The army of the British East India Company, led by Lord Cornwallis on 21 March 1791 captured the fort in the siege of Bangalore during the Third Mysore War (1790–1792).",
            "location": "Bangalore",
            "latitude": 12.962875,
            "longitude": 77.575956,
            "pincode": "560002"
        },
        {
            "id": 4,
            "name": "Bandstand Promenade",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/cover-1",
            "official_description": "The Bandstand Promenade is a kilometre long walkway along the sea on the west side of Bandra, a suburb of Mumbai, India. Less than a decade old, it is simultaneously a popular hangout spot, a jogging track, a park and also a lovers point.",
            "location": "Mumbai",
            "latitude": 19.0427179,
            "longitude": 72.8191316,
            "pincode": "400040"
        },
        {
            "id": 26,
            "name": "Baga Beach",
            "type": 4,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/kailash-giri-1.jpg",
            "official_description": "Baga a seaside town in Bardez, Goa, India. It comes under the jurisdiction of Calangute, which is 2 km south. Baga is known for its popular beach and Baga Creek. It is visited by thousands of tourists annually.",
            "location": "Goa",
            "latitude": 15.555694,
            "longitude": 73.751647,
            "pincode": "403516"
        },
        {
            "id": 23,
            "name": "Akshardham",
            "type": 2,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/Akshardam-cover.jpg",
            "official_description": "Akshardham' means the divine abode of God. It is hailed as an eternal place of devotion, purity and peace. Swaminarayan Akshardham at New Delhi is a Mandir – an abode of God, a Hindu house of worship, and a spiritual and cultural campus dedicated to devotion, learning and harmony. Timeless Hindu spiritual messages, vibrant devotional traditions and ancient architecture all are echoed in its art and architecture.",
            "location": "Delhi",
            "latitude": 28.585286,
            "longitude": 77.047037,
            "pincode": "110092"
        },
        {
            "id": 76,
            "name": "Agrasen ki Baoli",
            "type": 6,
            "cover": "https://s3-ap-southeast-1.amazonaws.com/heroskyrim/media/place_covers/210px-Ugrasen_ki_Baoli.JPG",
            "official_description": "Agrasen ki Baoli, designated a protected monument by the Archaeological Survey of India under the Ancient Monuments and Archaeological Sites and Remains Act of 1958, is a 60-meter long and 15-meter wide historical step well on Hailey Road near Connaught Place, Jantar Mantar in New Delhi, India. Although there are no known historical records to prove who built Agrasen ki Baoli, it is believed that it was originally built by the legendary king Agrasen during the Mahabharat epic era and rebuilt in the 14th century by the Agrawal community which traces its origin to Maharaja Agrasen.",
            "location": "Delhi",
            "latitude": 283734,
            "longitude": 771330,
            "pincode": "110001"
        }
    ]
};

export default PlacesList;